services:

  mssql-dev:

    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: mssql-dev

    environment:

      ACCEPT_EULA: "Y"

      SA_PASSWORD: "YourStrong!Passw0rd"

    ports:

      - "1433:1433"

    mem_limit: 3g

    restart: unless-stopped



  mongo-dev:

    image: mongo:6.0

    container_name: mongo-dev

    ports:

      - "27017:27017"

    restart: unless-stopped



  mongo-express:

    image: mongo-express

    container_name: mongo-express

    environment:

      ME_CONFIG_MONGODB_SERVER: mongo-dev

      ME_CONFIG_MONGODB_PORT: 27017

      ME_CONFIG_MONGODB_ADMINUSERNAME: root

      ME_CONFIG_MONGODB_ADMINPASSWORD: example

      ME_CONFIG_SITE_BASEURL: /

    ports:

      - "8081:8081"

    depends_on:

      - mongo-dev

    restart: unless-stopped

